#!bin/bash
alias sclinkedin_request_copy="echo 'Hi

I found my skill-set is aligned with the kind of people you are looking to recruit. I would like to add you to my professional network. I am graduating with a Masters in Computer Science this May from UNC-Chapel Hill.

-Tahsin' | pbcopy
"
alias scemail_signature_copy="echo 'Tahsin Kabir
Graduate Research Assistant,
The Department of Computer Science.
UNC-Chapel Hill
Email: tahsin@cs.unc.edu
Phone: 919-525-3042
LinkedIn: http://www.linkedin.com/in/tahsinkabir
' | pbcopy
"

alias scresume_link_copy="echo 'My resume can be downloaded from the following link: http://cs.unc.edu/~tahsin/Tahsin_Kabir_Resume.pdf' | pbcopy"
